---
layout: module
title: Econometric modeling
date: 2018-01-01 00:00:06
category: module
links:
  script: modeling.R
  data: els_plans.dta
output:
  md_document:
    variant: markdown_mmd
    preserve_yaml: true
    toc: true
    toc_depth: 2
---

```{r, include = FALSE, purl = FALSE}
source('knit_setup.R')
```
```{r, include = FALSE, purl = TRUE}
################################################################################
##
## <PROJ> R Workshop
## <FILE> modeling.R 
## <INIT> 16 January 2018
## <AUTH> Benjamin Skinner (GitHub/Twitter: @btskinner)
##
################################################################################

## clear memory
rm(list = ls())

## libraries
library(tidyverse)
library(haven)

```
```r
## libraries
library(tidyverse)
library(haven)
```

```{r, echo = FALSE, purl = FALSE, warnings = F, messages = F}
suppressMessages(library(tidyverse))
library(haven)

```

```{r}
## read in data
df <- read_dta('../data/els_plans.dta')

## create some 
df <- df %>%
    mutate(female = ifelse(bysex == 2, 0, bysex),
           moth_ba = ifelse(bymothed >= 6, 1, 0),
           fath_ba = ifelse(byfathed >= 6, 1, 0),
           par_ba = ifelse(bypared >= 6, 1, 0),
           lowinc = ifelse(byincome <= 7, 1, 0),
           pared_f = as_factor(bypared),
           race_f = as_factor(byrace),
           inc_f = as_factor(byincome),
           plan_col_grad = ifelse(bystexp >= 5, 1, 0))

```
# linear model
```{r}
## linear model
fit <- lm(bynels2m ~ bynels2r + byses1 + female + moth_ba + fath_ba,
          data = df)
fit

## get more information
summary(fit)

## add factors
fit <- lm(bynels2m ~ bynels2r + byses1 + female + moth_ba + fath_ba + lowinc
          + factor(byrace),
          data = df)
summary(fit)

## add factors created earlier
fit <- lm(bynels2m ~ byses1 + female + moth_ba + fath_ba + lowinc
          + race_f ,
          data = df)
summary(fit)

## add interactions
fit <- lm(bynels2m ~ byses1*lowinc + pared_f*lowinc, data = df)
summary(fit)

## add polynomials
fit <- lm(bynels2m ~ bynels2r + I(bynels2r^2) + I(bynels2r^3), data = df)
summary(fit)

```

# generalized linear model
```{r}
## logit
fit <- glm(plan_col_grad ~ bynels2m + pared_f,
           data = df,
           family = binomial(link = 'logit'))
summary(fit)

## probit
fit <- glm(plan_col_grad ~ bynels2m + pared_f,
           data = df,
           family = binomial(link = 'probit'))
summary(fit)

```

# predictions

```{r, echo = FALSE, purl = TRUE}
## -----------------------------------------------------------------------------
## 
## -----------------------------------------------------------------------------

```


```{r, echo = FALSE, purl = TRUE}

## =============================================================================
## END SCRIPT
################################################################################
```
